apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: azure-dash
spec:
  to:
    kind: Service
    name: azure-dash
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
