apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-dash
resources:
  - ../kubernetes
  - route.yaml
patches:
  - target: {kind: Deployment, name: azure-dash}
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: azure-dash-sp
            optional: true
