apiVersion: v1
kind: Secret
metadata:
  name: azure-dash-sp
  namespace: azure-dash
type: Opaque
stringData:
  AZURE_TENANT_ID: "00000000-0000-0000-0000-000000000000"
  AZURE_CLIENT_ID: "00000000-0000-0000-0000-000000000000"
  AZURE_CLIENT_SECRET: "replace-me"
